-- DROP TABLE PERSONA
CREATE TABLE PERSONA (
    PERSONA_ID SERIAL NOT NULL,
    GENERO_ID INTEGER NOT NULL,
    NOMBRE CHARACTER VARYING(90) NOT NULL,
    EDAD SMALLINT NOT NULL,
    IDENTIFICACION CHARACTER VARYING(10) NOT NULL,
    DIRECCION CHARACTER VARYING(90) NOT NULL,
    TELEFONO CHARACTER VARYING(10) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE PERSONA
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY (PERSONA_ID);

-- DROP TABLE GENERO
CREATE TABLE GENERO (
    GENERO_ID SERIAL NOT NULL,
    ABREVIATURA CHARACTER VARYING(2) NOT NULL,
    DESCRIPCION CHARACTER VARYING(30) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE GENERO
ALTER TABLE GENERO ADD CONSTRAINT GENERO_PK PRIMARY KEY (GENERO_ID);

-- DROP TABLE CLIENTE
CREATE TABLE CLIENTE (
    CLIENTE_ID SERIAL NOT NULL,
    PERSONA_ID INTEGER NOT NULL,
    CONTRASENA CHARACTER VARYING(30) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID);

-- DROP TABLE CUENTA
CREATE TABLE CUENTA (
    CUENTA_ID SERIAL NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    TIPO_CUENTA_ID INTEGER NOT NULL,
    NUMERO_CUENTA CHARACTER VARYING(30) NOT NULL,
    SALDO_INICIAL NUMERIC(19,2) NOT NULL,
    SALDO_ACTUAL NUMERIC(19,2) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_PK PRIMARY KEY (CUENTA_ID);

-- DROP TABLE TIPO_CUENTA
CREATE TABLE TIPO_CUENTA (
    TIPO_CUENTA_ID SERIAL NOT NULL,
    ABREVIATURA CHARACTER VARYING(2) NOT NULL,
    DESCRIPCION CHARACTER VARYING(30) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE TIPO_CUENTA
ALTER TABLE TIPO_CUENTA ADD CONSTRAINT TIPO_CUENTA_PK PRIMARY KEY (TIPO_CUENTA_ID);


-- DROP TABLE MOVIMIENTO
CREATE TABLE MOVIMIENTO (
    MOVIMIENTO_ID SERIAL NOT NULL,
    CUENTA_ID INTEGER NOT NULL,
    TIPO_MOVIMIENTO_ID INTEGER NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    VALOR NUMERIC(19,2) NOT NULL,
    SALDO NUMERIC(19,2) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE MOVIMIENTO
ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_PK PRIMARY KEY (MOVIMIENTO_ID);


-- DROP TABLE TIPO_MOVIMIENTO
CREATE TABLE TIPO_MOVIMIENTO (
    TIPO_MOVIMIENTO_ID SERIAL NOT NULL,
    ABREVIATURA CHARACTER VARYING(2) NOT NULL,
    DESCRIPCION CHARACTER VARYING(30) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

-- CREATE PK FOR TABLE TIPO_MOVIMIENTO
ALTER TABLE TIPO_MOVIMIENTO ADD CONSTRAINT TIPO_MOVIMIENTO_PK PRIMARY KEY (TIPO_MOVIMIENTO_ID);

-- CREATE FK FOR TABLE PERSONA
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_GENERO_FK FOREIGN KEY (GENERO_ID) 
    REFERENCES GENERO (GENERO_ID);

-- CREATE FK FOR TABLE CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PERSONA_FK FOREIGN KEY (PERSONA_ID) 
    REFERENCES PERSONA (PERSONA_ID);

-- CREATE FK FOR TABLE CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_CLIENTE_FK FOREIGN KEY (CLIENTE_ID) 
    REFERENCES CLIENTE (CLIENTE_ID);

-- CREATE FK FOR TABLE CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT CUENTA_TIPO_CUENTA_FK FOREIGN KEY (TIPO_CUENTA_ID) 
    REFERENCES TIPO_CUENTA (TIPO_CUENTA_ID);

-- CREATE FK FOR TABLE MOVIMIENTO
ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_CUENTA_FK FOREIGN KEY (CUENTA_ID) 
    REFERENCES CUENTA (CUENTA_ID);

-- CREATE FK FOR TABLE MOVIMIENTO
ALTER TABLE MOVIMIENTO ADD CONSTRAINT MOVIMIENTO_TIPO_MOVIMIENTO_FK FOREIGN KEY (TIPO_MOVIMIENTO_ID) 
    REFERENCES TIPO_MOVIMIENTO(TIPO_MOVIMIENTO_ID);